### PR TITLE
config: add etcd2 example to user_data sample

### PR DESCRIPTION
**Pull request by crawford**
Fixes https://github.com/coreos/coreos-vagrant/issues/224.

### CODE REVIEW

**Comment by termie** [comment]
heya, similar PR over at #226, you missed the config.rb changes and i had to explicitly stop etcd to get etcd2 to run

**Comment by termie** [comment]
p.s. i don't know why i have to explicitly stop etcd, i'm guessing something in a lower level config enables it somehow

**Comment by crawford** [comment]
Interesting. You shouldn't need to stop etcd. Fleet used to depend on it and start it, but I fixed that in the latest Alpha when we released etcd2.

**Comment by termie** [comment]
yeah, i don't really see where it would happen, maybe a systemd debug tool for "show me a dependency graph"?


# /usr/lib64/systemd/system/fleet.service
[Unit]
Description=fleet daemon

After=etcd.service
After=etcd2.service

Wants=fleet.socket
After=fleet.socket

**Comment by termie** [comment]
switching convo to my PR

**Pull request closed without merging**
