### PR TITLE
Rename vb_ vars to vm_ and enable for fusion

### PR DESCRIPTION
**Pull request by ryansch**
It was surprising to me as a new user that I couldn't specify memory and cpu variables independent of VM provider.

### CODE REVIEW

**Comment by bcwaldon** [comment]
@ryansch I'm in favor of the change, but we need to consider backwards-compatibility. Can you think of a reasonable approach that supports the existing vb_* variables as a fallback?

**Comment by ryansch** [comment]
@bcwaldon I took at stab at it using methods.

**Comment by bcwaldon** [comment]
LGTM after you squash your commits down to one and rebase off of master

**Comment by ryansch** [comment]
Rebased and squashed!

**Comment by bcwaldon** [comment]
Thanks!

**Pull request merged**
